remote: origin
target-branch: master
chart-dirs:
  - charts
helm-extra-args: "--timeout 600s"  
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false
