---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.0
  name: rulestatuses.capsule.clastix.io
spec:
  group: capsule.clastix.io
  names:
    kind: RuleStatus
    listKind: RuleStatusList
    plural: rulestatuses
    singular: rulestatus
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          status:
            description: RuleStatus contains the accumulated rules applying to namespace
              it's deployed in.
            properties:
              rule:
                description: Managed Enforcement properties per Namespace (aggregated
                  from rules)
                properties:
                  enforce:
                    description: Enforcement Rules applied
                    properties:
                      registries:
                        description: |-
                          Define registries which are allowed to be used within this tenant
                          The rules are aggregated, since you can use Regular Expressions the match registry endpoints
                        items:
                          properties:
                            policy:
                              description: Allowed PullPolicy for the given registry.
                                Supplying no value allows all policies.
                              items:
                                description: PullPolicy describes a policy for if/when
                                  to pull a container image
                                type: string
                              type: array
                            url:
                              description: OCI Registry endpoint, is treated as regular
                                expression.
                              type: string
                            validation:
                              default:
                              - pod/images
                              - pod/volumes
                              description: Requesting Resources
                              items:
                                enum:
                                - pod/images
                                - pod/volumes
                                type: string
                              type: array
                          required:
                          - url
                          type: object
                        type: array
                    type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
