---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-example
spec:
  project: default
  source:
    path: gitops/simple/
    repoURL: 'https://github.com/projectcapsule/examples.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
