{{- if not $.Values.crds.exclusive }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capsule.pre-delete.name" . }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-4"
    {{- include "capsule.pre-delete.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "capsule.pre-delete.component" . | quote }}
    {{- include "capsule.labels" . | nindent 4 }}
{{- end }}